**Run this Jupyter Notebook**
- Run this Notebook via [**Google Colab Platform**](https://colab.research.google.com/github/mhmaem/data_science_university/blob/master/02_numpy_interactive_cheatsheets/02_01_numby_basics.ipynb)
- Download this [**Notebook**](https://github.com/mhmaem/data_science_university/blob/master/02_numpy_interactive_cheatsheets/02_01_numby_basics.ipynb) to run it locally

---
---
# **NumPy**
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays, NumPy is using C to to achieve extraordinary performance

## **Importing**

In [1]:
import numpy as np

---
## **Creating and Initializing Arrays**
NumPy arrays must have all elements of the same type

In [2]:
single_row_array = np.array([1,2,3])
single_row_array

array([1, 2, 3])

In [3]:
two_dimensions_array = np.array([(1.5,2,3), (4,6,5)], dtype = float)
two_dimensions_array

array([[1.5, 2. , 3. ],
       [4. , 6. , 5. ]])

In [4]:
three_dimensions_array = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (7,8,9)]], dtype = float)
three_dimensions_array

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [7. , 8. , 9. ]]])

### **Initializing Special Arrays**

In [5]:
np.zeros((3,4))    # Array of zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4),dtype=np.int16)    # Array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
range_array = np.arange(10,25,5)    # Array of a range of steps
range_array

array([10, 15, 20])

In [8]:
np.linspace(0,2,9)   # Array of evenly spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
constant_array = np.full((2,2),7)    # Array of a constant
constant_array

array([[7, 7],
       [7, 7]])

In [10]:
identity_matrix = np.eye(2)    # Identity Matrix
identity_matrix

array([[1., 0.],
       [0., 1.]])

In [11]:
np.random.random((2,2))    # Array with random values

array([[0.54344988, 0.56194026],
       [0.98727716, 0.08418047]])

In [12]:
np.empty((3,2))    # Empty Array

array([[1.5, 2. ],
       [3. , 4. ],
       [6. , 5. ]])

---
## **NumPy Data Types**
| Data Type | Definition |
|--|--|
| np.int64 | Signed 64-bit integer types |
| np.float32 | Standard double-precision floating point |
| np.complex | Complex numbers represented by 128 floats |
| np.bool | Boolean type storing TRUE and FALSE values |
| np.object | Python object type |
| np.string | Fixed-length string type |
| np.unicode | Fixed-length Unicode type |

---
## **Array Details**

In [13]:
three_dimensions_array.shape

(2, 2, 3)

In [14]:
len(three_dimensions_array)

2

In [15]:
three_dimensions_array.ndim

3

In [16]:
three_dimensions_array.size

12

In [17]:
three_dimensions_array.dtype

dtype('float64')

In [18]:
three_dimensions_array.dtype.name

'float64'

In [19]:
two_dimensions_array.astype(int)

array([[1, 2, 3],
       [4, 6, 5]])

---
## **Array Operations**
### **Arithmetic**

In [20]:
single_row_array - two_dimensions_array

array([[-0.5,  0. ,  0. ],
       [-3. , -4. , -2. ]])

In [21]:
np.subtract(single_row_array, two_dimensions_array)

array([[-0.5,  0. ,  0. ],
       [-3. , -4. , -2. ]])

In [22]:
two_dimensions_array + single_row_array

array([[2.5, 4. , 6. ],
       [5. , 8. , 8. ]])

In [23]:
np.add(two_dimensions_array, single_row_array)

array([[2.5, 4. , 6. ],
       [5. , 8. , 8. ]])

In [24]:
single_row_array / two_dimensions_array

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.33333333, 0.6       ]])

In [25]:
np.divide(single_row_array, two_dimensions_array)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.33333333, 0.6       ]])

In [26]:
single_row_array * two_dimensions_array

array([[ 1.5,  4. ,  9. ],
       [ 4. , 12. , 15. ]])

In [27]:
np.multiply(single_row_array, two_dimensions_array)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 12. , 15. ]])

In [28]:
np.exp(three_dimensions_array)

array([[[4.48168907e+00, 7.38905610e+00, 2.00855369e+01],
        [5.45981500e+01, 1.48413159e+02, 4.03428793e+02]],

       [[2.00855369e+01, 7.38905610e+00, 2.71828183e+00],
        [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]]])

In [29]:
np.sqrt(three_dimensions_array)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.64575131, 2.82842712, 3.        ]]])

In [30]:
np.sin(three_dimensions_array)

array([[[ 0.99749499,  0.90929743,  0.14112001],
        [-0.7568025 , -0.95892427, -0.2794155 ]],

       [[ 0.14112001,  0.90929743,  0.84147098],
        [ 0.6569866 ,  0.98935825,  0.41211849]]])

In [31]:
np.cos(three_dimensions_array)

array([[[ 0.0707372 , -0.41614684, -0.9899925 ],
        [-0.65364362,  0.28366219,  0.96017029]],

       [[-0.9899925 , -0.41614684,  0.54030231],
        [ 0.75390225, -0.14550003, -0.91113026]]])

In [32]:
np.log(three_dimensions_array)

array([[[0.40546511, 0.69314718, 1.09861229],
        [1.38629436, 1.60943791, 1.79175947]],

       [[1.09861229, 0.69314718, 0.        ],
        [1.94591015, 2.07944154, 2.19722458]]])

In [33]:
constant_array.dot(identity_matrix)

array([[7., 7.],
       [7., 7.]])

### **Aggregations**

In [34]:
three_dimensions_array.sum()

51.5

In [35]:
three_dimensions_array.min()

1.0

In [36]:
three_dimensions_array.max()

9.0

In [37]:
three_dimensions_array.max(axis=0)

array([[3., 2., 3.],
       [7., 8., 9.]])

In [38]:
three_dimensions_array.cumsum(axis=1)

array([[[ 1.5,  2. ,  3. ],
        [ 5.5,  7. ,  9. ]],

       [[ 3. ,  2. ,  1. ],
        [10. , 10. , 10. ]]])

In [39]:
np.mean(three_dimensions_array)

4.291666666666667

In [40]:
np.median(three_dimensions_array)

3.5

In [41]:
np.corrcoef(two_dimensions_array)

array([[1.        , 0.32732684],
       [0.32732684, 1.        ]])

In [42]:
np.std(three_dimensions_array)

2.569519518422765

### **Array Comparison**

In [43]:
single_row_array == two_dimensions_array

array([[False,  True,  True],
       [False, False, False]])

In [44]:
single_row_array < 2

array([ True, False, False])

In [45]:
np.array_equal(single_row_array, two_dimensions_array)

False

### **Array Copy**

In [46]:
shadow_copy = three_dimensions_array.view()
shadow_copy

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [7. , 8. , 9. ]]])

In [47]:
top_level_copy = np.copy(three_dimensions_array)
top_level_copy

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [7. , 8. , 9. ]]])

In [48]:
deep_copy = three_dimensions_array.copy()
deep_copy

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [7. , 8. , 9. ]]])

### **Array Sorting**

In [49]:
two_dimensions_array.sort()
two_dimensions_array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [50]:
three_dimensions_array.sort(axis=0)
three_dimensions_array

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [7. , 8. , 9. ]]])

---
## **Array Subsitting**
### **Elements Accessing**

In [51]:
single_row_array[1]

2

In [52]:
two_dimensions_array[1,2]

6.0

### **Slicing**

In [53]:
single_row_array[0:2]

array([1, 2])

In [54]:
two_dimensions_array[0:2,1]

array([2., 5.])

In [55]:
two_dimensions_array[:1]

array([[1.5, 2. , 3. ]])

In [56]:
three_dimensions_array[1,...]

array([[3., 2., 3.],
       [7., 8., 9.]])

In [57]:
single_row_array[ : :-1]

array([3, 2, 1])

### **Boolean Indexing**

In [58]:
single_row_array[single_row_array<2]

array([1])

### **Fancy Indexing**

In [59]:
two_dimensions_array[[1, 0, 1, 0],[0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [60]:
two_dimensions_array[[1, 0, 1, 0]][:,[0,1,2,0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

---
## **Array Manipulation**
### **Transposing Array**

In [61]:
np.transpose(two_dimensions_array)

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

### **Reshaping**

In [62]:
two_dimensions_array.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [63]:
two_dimensions_array

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [64]:
two_dimensions_array.reshape(3,2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [65]:
two_dimensions_array.reshape(3,-2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### **Adding/Removing Elements**

In [66]:
shadow_copy.resize((2,6))
shadow_copy

array([[1.5, 2. , 1. , 4. , 5. , 6. ],
       [3. , 2. , 3. , 7. , 8. , 9. ]])

In [67]:
np.append(shadow_copy, two_dimensions_array)

array([1.5, 2. , 1. , 4. , 5. , 6. , 3. , 2. , 3. , 7. , 8. , 9. , 1.5,
       2. , 3. , 4. , 5. , 6. ])

In [68]:
np.insert(single_row_array, 1, 5)

array([1, 5, 2, 3])

In [69]:
np.delete(single_row_array,[1])

array([1, 3])

### **Combining Arrays**

In [70]:
np.concatenate((single_row_array,range_array),axis=0)

array([ 1,  2,  3, 10, 15, 20])

In [71]:
np.vstack((single_row_array,two_dimensions_array))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [72]:
np.hstack((constant_array,identity_matrix))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [73]:
np.column_stack((single_row_array,range_array))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### **Splitting Arrays**

In [74]:
np.hsplit(single_row_array,3)

[array([1]), array([2]), array([3])]

In [75]:
np.vsplit(three_dimensions_array,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [7., 8., 9.]]])]